name: Docker Image CI

on:
  push: # push 时触发ci
    branches: [main] # 作用于main分支
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 拉取main分支代码
      - name: Checkout
        uses: actions/checkout@v2

      # # 指定nodejs版本
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "yarn"

      # # 安装依赖
      # - name: install
      #   run: sudo yarn install

      # # 打包
      # - name: build
      #   run: sudo yarn run build

      # 制作docker镜像并推送到阿里云容器镜像服务
      - name: build and push docker image
        run: |
          docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }}
          docker image build -t myblob:latest .
          docker tag myblob registry.cn-hangzhou.aliyuncs.com/test-blog/blog:latest
          docker push registry.cn-hangzhou.aliyuncs.com/test-blog/blog:latest
